version: '3.8'

services:
  blog-backend:
    image: ghcr.io/saverbox/blog-backend:1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: secret
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/blogdb
    depends_on:
      - redpanda
      - database
    networks:
      - blog-network
    ports:
      - "8080:8080"

  validation-service:
    image: ghcr.io/saverbox/validation:1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - blog-network


  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v23.3.5
    command:
      - start
      - --advertise-kafka-addr redpanda:9092
    ports:
      - 9092:9092
      - 8082:8082
      - 8081:8081
      - 9644:9644
    networks:
      - blog-network

  database:
    image: postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
